name 'node_oracledb'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures node_oracledb'
long_description 'Installs/Configures node_oracledb'
version '0.1.0'
