SELECT
  date_update                   "dateUpdate"
 ,esb_message_meta_nr          "esbMessageMetaNr"
 ,esb_message_master_nr        "esbMessageMasterNr"
 ,esb_message_type             "esbMessageType"
 ,output_request_setup_task_nr "outputRequestSetupTaskNr"
 ,process_status               "processStatus"
 ,error_msg                    "errorMsg"
 ,destination_type             "destinationType"
 ,destination                  "destination"
 ,output_name                  "outputName"
 ,userid_requestor             "useridRequestor"
 ,emailaddress_requestor       "emailaddressRequestor"
 ,msg_description              "msgDescription"
 ,aggregator_id                "aggregatorId"
 ,aggregator_count             "aggregatorCount"
 ,priority                     "priority"
 ,layout_code                  "layoutCode"
 ,source_key_type              "sourceKeyType"
 ,source_key_id                "sourceKeyId"
 ,site_nr                      "siteNr"
 ,company_nr                   "companyNr"
 ,datetime_requested           "datetimeRequested"
--,additional_payload           "additionalPayload"
 ,destination_site_nr          "destinationSiteNr"
 ,esb_message_sub_type         "esbMessageSubType"      
FROM   trading.esb_message_meta r
WHERE  REGEXP_SUBSTR(r.aggregator_id, '[0-9]*') = :main_doc_registration_nr